# site settings
title: Liquid Perfection 
subtitle: 
email: liquidperfectionjax@gmail.com
description: 	<form action="https://webto.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8" method="POST"><input type=hidden name='captcha_settings' value='{"keyname":"liquidperfectionjax1","fallback":"true","orgId":"00DDn000007qQ3h","ts":""}'><input type=hidden name="oid" value="00DDn000007qQ3h"><input type=hidden name="retURL" value="https://cygnus69.github.io/liquidperfectionjax/"><div><label for="first_name">First Name</label><input  id="first_name" maxlength="40" name="first_name" size="20" type="text" /></div><div><label for="last_name">Last Name</label><input  id="last_name" maxlength="80" name="last_name" size="20" type="text" /></div><div><label for="phone">Phone</label><input  id="phone" maxlength="40" name="phone" size="20" type="text" /></div><div><label for="email">Email</label><input  id="email" maxlength="80" name="email" size="20" type="text" /></div><div><label for="flooring_type">Flooring Type</label><select  id="00NDn00000Y6MtT" name="00NDn00000Y6MtT" title="Flooring Type"><option value="">--None--</option><option value="HERMETIC Aircraft">HERMETIC&#8482 Aircraft</option><option value="HERMETIC Flake">HERMETIC&#8482 Flake</option><option value="HERMETIC Neat">HERMETIC&#8482 Neat</option><option value="HERMETIC Paramount">HERMETIC&#8482 Paramount</option><option value="HERMETIC Paramount HD">HERMETIC&#8482 Paramount HD</option><option value="HERMETIC Quartz">HERMETIC&#8482 Quartz</option><option value="HERMETIC Stout">HERMETIC&#8482 Stout</option><option value="HERMETIC Urethane Cement Slurry">HERMETIC&#8482 Urethane Cement Slurry</option><option value="REFLECTOR Enhancer">REFLECTOR&#8482 Enhancer</option></select></div><div><label for="type_of_space">Type of Space:</label><select  id="00NDn00000WZYtD" name="00NDn00000WZYtD" title="Type of Space"><option value="">--None--</option><option value="Bathroom">Bathroom</option><option value="Bedroom">Bedroom</option><option value="Business">Business</option><option value="Dining Room">Dining Room</option><option value="Foyer">Foyer</option><option value="Garage">Garage</option><option value="House">House</option><option value="Kitchen">Kitchen</option><option value="Laundry Room">Laundry Room</option><option value="Man Cave">Man Cave</option><option value="Office">Office</option><option value="Patio">Patio</option><option value="Shed">Shed</option><option value="Theater">Theater</option><option value="Warehouse">Warehouse</option></select></div><div><label for="interest">Interest:</label><select  id="00NDn00000WZMfm" name="00NDn00000WZMfm" title="Interest"><option value="">--None--</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option><option value="6">6</option><option value="7">7</option><option value="8">8</option><option value="9">9</option><option value="10">10</option></select></div><div><label for="zip">Zip Code</label><input  id="zip" maxlength="20" name="zip" size="20" type="text" /><br><div class="g-recaptcha" data-sitekey="6Lc-Q1IkAAAAAMs0JSQrvG4DLBby6A-bSiWqbzs6"></div><div><input type="submit" name="submit"></div></form>
baseurl: "/liquidperfectionjax" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 3051 Waters View Circle
city: Orange Park
state: FL
zip_code: 32073
country: United States of America
phone: (904) 844-9766

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook: https://www.facebook.com/Liquid-Perfection-1374511976188884/
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
